define(['gmobile'],
    function(GMobileJS) {
        GMobileJS.notUsejQueryMobile = true;
        var App = new GMobileJS.App({
            controller: 'Controller',
            collections: [
            ],
            models: [
            ],
            views: [
                'PluginsView',
                'LoginView',
                'BatteryView',
                'CameraView',
                'ContactsView',
                'DeviceView',
                'DeviceMotionView',
                'DeviceOrientationView',
                'DialogsView',
                'FileView',
                'GeolocationView',
                'GlobalizationView',
                'InappBrowserView',
                'MediaView',
                'MediaCaptureView',
                'NetworkInformationView',
                'SplashScreenView',
                'StatusBarView',
                'VibrationView',
                'SlideView',
                'STTView',
                'ScanView',
                'NFCView',
                'MocklocationView',
                'GCMView'
            ],
            templates: [
                'PluginsTemplate',
                'LoginTemplate',
                'BatteryTemplate',
                'CameraTemplate',
                'ContactsTemplate',
                'DeviceTemplate',
                'DeviceMotionTemplate',
                'DeviceOrientationTemplate',
                'DialogsTemplate',
                'FileTemplate',
                'GeolocationTemplate',
                'GlobalizationTemplate',
                'InappBrowserTemplate',
                'MediaTemplate',
                'MediaCaptureTemplate',
                'NetworkInformationTemplate',
                'SlideTemplate',
                'SplashScreenTemplate',
                'StatusBarTemplate',
                'VibrationTemplate',
                'STTTemplate',
                'ScanTemplate',
                'NFCTemplate',
                'MocklocationTemplate',
                'GCMTemplate'
            ],
            appRoutes: {
                'plugins': 'nav_plugins',
                'login': 'nav_login',
                'battery': 'nav_battery',
                'camera': 'nav_camera',
                'contacts': 'nav_contacts',
                'device': 'nav_device',
                'devicemotion': 'nav_devicemotion',
                'deviceorientation': 'nav_deviceorientation',
                'dialogs': 'nav_dialogs',
                'file': 'nav_file',
                'geolocation': 'nav_geolocation',
                'globalization': 'nav_globalization',
                'inappbrowser': 'nav_inappbrowser',
                'media': 'nav_media',
                'mediacapture': 'nav_mediacapture',
                'networkinformation': 'nav_networkinformation',
                'splashscreen': 'nav_splashscreen',
                'statusbar': 'nav_statusbar',
                'vibration': 'nav_vibration',
                'stt': 'nav_stt',
                'scan': 'nav_scan',
                'nfc': 'nav_nfc',
                'mocklocation': 'nav_mocklocation',
                'gcm': 'nav_gcm',
                '*actions': 'nav_default'
            }
        });
        return App;
    }
);
